name: Build & Test
"on":
  push:
    branches:
    - '*'
  pull_request:
    branches:
    - '*'
  schedule:
  - cron: 01 13 * * SAT
jobs:
  build:
    strategy:
      fail-fast: false # https://github.com/orgs/community/discussions/27192#discussioncomment-3254966
      matrix:
        os:
        - ubuntu-latest
        - macOS-latest
        - windows-latest
    runs-on: ${{ matrix.os }}
    name: Build & Test
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v4
      with:
        go-version: "1.21"
    - name: Build & Test
      run: |
        go install mvdan.cc/gofumpt@latest
        go test ./...
    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v4
      with:
        args: release --snapshot --skip-publish --clean
    - name: Test Windows
      if: runner.os == 'Windows'
      run: bazel run //cmd:navylie -- -- --verbose --dir myproject
    - name: Test Other
      if: runner.os != 'Windows'
      run: bazel run //cmd:navylie -- --verbose --dir myproject

