name: Build & Test
"on":
  push:
    branches:
    - '*'
  pull_request:
    branches:
    - '*'
  schedule:
  - cron: 01 13 * * SAT
jobs:
  build:
    strategy:
      fail-fast: false # https://github.com/orgs/community/discussions/27192#discussioncomment-3254966
      matrix:
        os:
        - ubuntu-latest
        - macOS-latest
        - windows-latest
    runs-on: ${{ matrix.os }}
    name: Build & Test
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: "1.21"
    - name: Build & Test
      run: |
        go install mvdan.cc/gofumpt@latest
        go test ./...
    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v6
      with:
        args: release --snapshot --skip=publish --clean

    - name: Test Windows 1
      if: runner.os == 'Windows'
      run: |
        bazel run //cmd:navylie -- -- --verbose --dir c:/Windows/Temp/myproject
        cd c:/Windows/Temp/myproject
        bazel --output_base=c:/Windows/Temp/bazel_output_base run //cmd:myproject -- -- --verbose
    - name: Test Windows 2
      if: runner.os == 'Windows'
      run: |
        bazel run //cmd:navylie -- -- --verbose --dir c:/Windows/Temp/myproject2
        cd c:/Windows/Temp/myproject2
        bazel --output_base=c:/Windows/Temp/bazel_output_base run //cmd:myproject2 -- -- --verbose

    - name: Test Other 1
      if: runner.os != 'Windows'
      run: |
        bazel run //cmd:navylie -- --verbose --dir /tmp/myproject
        cd /tmp/myproject
        bazel run //cmd:myproject -- --verbose
    - name: Test Other 2
      if: runner.os != 'Windows'
      run: |
        bazel run //cmd:navylie -- --verbose --dir /tmp/myproject2
        cd /tmp/myproject2
        bazel run //cmd:myproject2 -- --verbose
